# Generated by Django 5.0.6 on 2024-06-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_todo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='isdone',
            field=models.BooleanField(default=False),
        ),
    ]
